runtime: python37

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "/Users/amalinverni/Desktop/github-wikigame/tuxgame/my-project-1509808152396-6823ad5c6a5d.json"
  PYTHONIOENCODING: 'utf-8'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app